### ISSUE TITLE
PrimeFaces 13

### ISSUE THREAD

**Issue by melloware** [primefaces-extensions/faces-intellisense#12]
Need to add PrimeFaces and PFE 13 Taglibs

**Comment by per-steinar** [comment]
I have created a small powershell tool to parse Java docs into json for this purpose.

https://github.com/per-steinar/richtools

However, the long term solution must be to detekt taglib.xml files on class path and use those directly.

**Comment by melloware** [comment]
Thanks it looks like Leo just responded how he does it!
