### ISSUE TITLE
README: How to generate a new taglib JSON?

### ISSUE THREAD

**Issue by melloware** [primefaces-extensions/faces-intellisense#14]
We need to add to the readme how to add a new lib version for example PrimeFaces 13 etc.

**Comment by melloware** [comment]
cc @leosj29

**Comment by leosj29** [comment]
Greetings! I used this custom development tool: [https://github.com/leosj29/taglibs-faces-generator](https://github.com/leosj29/taglibs-faces-generator)

**Comment by melloware** [comment]
Thank you!

**Comment by melloware** [comment]
I moved the generator into this project and updated the readme.

**Comment by melloware** [comment]
@leosj29 do you mind updating your README.MD to point to this fork please?
