### ISSUE TITLE
Deprecate "JSF Primefaces Intellisense" and point it to "Jakarta Faces Intellisense"

### ISSUE THREAD

**Issue by FlipWarthog** [primefaces-extensions/faces-intellisense#20]
Since this new fork is live, the old one should be deprecated in the Visual Studio Marketplace and point to this new extension.

Archived repo: https://github.com/leosj29/jsf-primefaces-intellisense
Original extension: https://marketplace.visualstudio.com/items?itemName=leosj29.jsf-primefaces-intellisense

New Extension: https://marketplace.visualstudio.com/items?itemName=FlipWarthog.faces-intellisense

**Comment by melloware** [comment]
cc @leosj29 is there any way you can deprecate or remove your old extension and update your GitHub report to point to this repo?

**Comment by leosj29** [comment]
Sorry for the delay, I already put a notification in the previous repo and unpublished the extension.

**Comment by melloware** [comment]
thanks!
