### ISSUE TITLE
Hover: `h:`and `f:` components not hovering

### ISSUE THREAD

**Issue by melloware** [primefaces-extensions/faces-intellisense#27]
![image](https://github.com/user-attachments/assets/7eeb8b71-9106-48ef-a7cb-3544d66dcf98)

**Comment by melloware** [comment]
I think we need to check that it works for both Jakarta Namespace and Javax namespace. In my example above I was using.

```xml
<html xmlns="http://www.w3.org/1999/xhtml"
      xmlns:h="http://xmlns.jcp.org/jsf/html"
      xmlns:f="http://xmlns.jcp.org/jsf/core"
      xmlns:p="http://primefaces.org/ui">
```

**Comment by FlipWarthog** [comment]
It should already be handling the Jakarta namespaces here: https://github.com/primefaces-extensions/faces-intellisense/blob/f4e06c3c5302aeb8bc91371c083118fb7019d2d8/src/extension.ts#L71-L74

Using this function: https://github.com/primefaces-extensions/faces-intellisense/blob/f4e06c3c5302aeb8bc91371c083118fb7019d2d8/src/extension.ts#L495-L501

Could be we need to double check that conditional to make sure it's actually working?

**Comment by melloware** [comment]
Yep PF showcase is 4.0 and PF Integrations Tests are 2.3 and I have both open in the same VSCode workspace.
