### ISSUE TITLE
allow interpolation in style attribute of primeface component

### ISSUE THREAD

**Issue by DebasishWe** [primefaces-extensions/faces-intellisense#38]
while using jsf assignment inside other attributes, no validation check done and no error is shown but while using jsf assigment from bean on style attribute error displays. this error should not be displayed. it is intended behaviour

**Comment by melloware** [comment]
@DebasishWe can you show screenshots of what you mean?  I am having a little trouble understanding the issue?

**Comment by DebasishWe** [comment]
![Screenshot from 2024-09-25 17-48-35](https://github.com/user-attachments/assets/affaf0f0-4924-49f0-a944-e43df6001bc7)
@melloware in this scrrenshot even if style atttribute is correct, it is shown as error. Can this error be removed for this attribute like other attributes. Same also true for script tag.

**Comment by melloware** [comment]
Ahhh @FlipWarthog i am not sure if this is a Faces Intellisense issue or the fact VScode is treating XHTML as an HTML dialect and thinks the syntax is incorrect?

**Comment by FlipWarthog** [comment]
Yeah, I think it's the HTML validator in VSCode. If you open a file, VSCode will display the language activated in the bottom right; for XHTML it picks up as HTML:

![image](https://github.com/user-attachments/assets/7d4a040a-f977-4fcd-96c7-02812fc7adfb)

**Comment by FlipWarthog** [comment]
More specifically, it's the built in CSS validator that is not aware of JSF syntax. Nothing we can do there.

**Comment by melloware** [comment]
@all-contributors add @userTesting for userTesting

**Comment by melloware** [comment]
@all-contributors add @DebasishWe for userTesting
