### ISSUE TITLE
Intellisense not working when attributes are on separate lines

### ISSUE THREAD

**Issue by jbrower2** [primefaces-extensions/faces-intellisense#42]
For the following code snippet, the `id` attribute is able to be hovered over, but all of the other attributes don't have any hover information:

```xml
			<p:dialog
				id="#{cc.widgetVar}"
				widgetVar="#{cc.widgetVar}"
				header="#{cc.header}"
				closable="false"
				minimizable="#{cc.minimizable}"
				modal="#{cc.modal}">
				<cc:insertChildren />
			</p:dialog>
```

I suspect this is a bug in the parsing logic in `getComponentInformation`, and might be due to the tabs in my source code.

**Comment by melloware** [comment]
Thanks @jbrower2 !

**Comment by melloware** [comment]
@all-contributors add @jbrower2 for bug
