### ISSUE TITLE
Renaming fork

### ISSUE THREAD

**Issue by per-steinar** [primefaces-extensions/faces-intellisense#6]
Before publishing the forked extension the extension should be renamed to reflect it not only supporting prime faces.

**Comment by melloware** [comment]
oh yeah and it should be called `faces-intellisense` as its not JSF anymore and its generic.

**Comment by per-steinar** [comment]
"Intellisense for Jakarta Faces" could be an alternative. We need to ensure that we don't step into any trademark issues.
https://jakarta.ee/legal/trademark_guidelines/

**Comment by melloware** [comment]
I like just Intellisense for Faces it keeps Jakarta out of it?

**Comment by per-steinar** [comment]
As long as it isn't too vague. I'm not familiar with any similar technologies that uses the term faces to describe it self.

**Comment by melloware** [comment]
OK I see maybe a better would be `"Intellisense for Java Faces"`   I don't like restricting it to just Jakarta since its really a Java based tech?

**Comment by per-steinar** [comment]
JSF was a part of Java EE. Java EE was handed over to the Eclipse Foundation and renamed to Jakarta EE, due to trademark issues. The latest release is released under the name Jakarta Faces. I think I would be best to use the current name of the technology, even though it is still referred to by its old name.

However un the end, this is your call as owner of the repository.

**Comment by melloware** [comment]
Here is what I put in the new package.json

```js
  "name": "faces-intellisense",
  "displayName": "Jakarta Faces Intellisense",
  "description": "Jakarta Faces Intellisense provides components completion in the HTML, XHTML and Jakarta Faces. Based on the official Tag Library definitions.",
```

**Comment by per-steinar** [comment]
That's probably the best solution. You don't have to change the name if they renames JSF again
